version: '3.4'

services:
  teamcity-agent:
    image: teamcity-agent
    ports:
      - "9090:9090"
    volumes:
      - ./teamcity-agent-logs:/TeamAgent/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Seoul
      - SERVER_URL=http://192.168.0.20:8111/