version: '3.4'

services:
  teamcity-agent:
    image: teamcity-agent
    user: '0'
    ports:
      - "9090:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - teamcity_volume:/buildagent

    environment:
      - TZ=Asia/Seoul
      - SERVER_URL=http://192.168.0.10:8111/

volumes:
  teamcity_volume:
