version: '3.4'

services:
  teamcity-agent:
    image: teamcity-agent
    user: '0'
    ports:
      - "9090:9090"
    volumes:
      - /opt/buildagent/logs:/opt/buildagent/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/buildagent/work:/opt/buildagent/work
      - /opt/buildagent/temp:/opt/buildagent/temp
      - /opt/buildagent/tools:/opt/buildagent/tools
      - /opt/buildagent/plugins:/opt/buildagent/plugins
      - /opt/buildagent/system:/opt/buildagent/system

    environment:
      - TZ=Asia/Seoul
      - SERVER_URL=http://192.168.0.20:8111/