version: '3.4'

services:
  teamcity-agent:
    image: agent-test
    ports:
      - "9090:9090"
    volumes:
      - ./teamcity-agent-logs:/TeamAgent/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "TZ=Asia/Seoul"