version: '3.4'

services:
  teamcity-server:
    image: teamcity-test
    ports:
      - "8111:8111"
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./teamcity-server-logs:/TeamCity/logs
    environment:
      - "TZ=Asia/Seoul"


  teamcity-agent:
    image: agent-test
    ports:
      - "9090:9090"
    volumes:
      - ./teamcity-agent-logs:/TeamAgent/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "TZ=Asia/Seoul"