FROM openjdk:11

WORKDIR /

# dist copy
COPY ./dist/Agent ./TeamAgent

# extra
COPY ./teamcity-agent-conf/buildAgent.properties /TeamAgent/conf
COPY ./teamcity-agent-conf/start.sh /

ENTRYPOINT ./start.sh