FROM ubuntu:20.04

RUN apt-get update 
RUN apt-get upgrade -y

# 한글깨짐 관련
RUN apt-get install language-pack-ko -y
RUN locale-gen ko_KR.UTF-8
ENV LC_ALL=ko_KR.UTF-8
ENV LANG=ko_KR.UTF-8
##

# JDK Setup
RUN apt-get install openjdk-11-jdk -y

RUN export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
RUN export PATH=$PATH:$JAVA_HOME/bin
##

# Docker Setup
RUN apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release -y

RUN mkdir -p /etc/apt/keyrings

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get update

RUN apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y

RUN systemctl enable docker.service
RUN systemctl enable containerd.service
##

WORKDIR /

# dist copy
COPY ./dist/Agent ./TeamAgent

# extra
COPY ./teamcity-agent-conf/start.sh /

ENTRYPOINT ./start.sh